version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://toanplq:061191@cluster0-shard-00-00.z15fs.mongodb.net:27017,cluster0-shard-00-01.z15fs.mongodb.net:27017,cluster0-shard-00-02.z15fs.mongodb.net:27017/Cluster0?ssl=true&replicaSet=atlas-co08ew-shard-0&authSource=admin&retryWrites=true&w=majority
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
